name: Build wheels

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

env:
  PACKAGE_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.0' }}

jobs:
  build_wheels:
    name: Wheels ${{ matrix.tag }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest,    arch: x86_64,  libc: manylinux, image: "quay.io/pypa/manylinux_2_28_x86_64", tag: manylinux_2_28 }
          - { os: ubuntu-24.04-arm, arch: aarch64, libc: manylinux, image: "quay.io/pypa/manylinux_2_28_aarch64", tag: manylinux_2_28 }
          - { os: ubuntu-latest,    arch: x86_64,  libc: manylinux, image: "quay.io/pypa/manylinux_2_34_x86_64", tag: manylinux_2_34 }
          - { os: ubuntu-24.04-arm, arch: aarch64, libc: manylinux, image: "quay.io/pypa/manylinux_2_34_aarch64", tag: manylinux_2_34 }
          - { os: ubuntu-latest,    arch: x86_64,  libc: musllinux, image: "quay.io/pypa/musllinux_1_2_x86_64", tag: musllinux_1_2 }
          - { os: ubuntu-24.04-arm, arch: aarch64, libc: musllinux, image: "quay.io/pypa/musllinux_1_2_aarch64", tag: musllinux_1_2 }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set version from tag
        run: sed -i "s/version=\".*\"/version=\"${PACKAGE_VERSION#v}\"/" setup.py

      - uses: pypa/cibuildwheel@v2.23
        env:
          CIBW_BUILD: "cp310-${{ matrix.libc }}* cp311-${{ matrix.libc }}* cp312-${{ matrix.libc }}* cp313-${{ matrix.libc }}* cp314-${{ matrix.libc }}*"
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.image }}
          CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.image }}
          CIBW_MUSLLINUX_X86_64_IMAGE: ${{ matrix.image }}
          CIBW_MUSLLINUX_AARCH64_IMAGE: ${{ matrix.image }}
          CIBW_BUILD_VERBOSITY: 1
        with:
          output-dir: dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.tag }}-${{ matrix.arch }}
          path: dist/*.whl

  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set version from tag
        run: sed -i "s/version=\".*\"/version=\"${PACKAGE_VERSION#v}\"/" setup.py

      - run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  publish:
    name: Publish to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1

  release:
    name: Upload release assets
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Upload assets to GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload "${{ github.event.release.tag_name }}" dist/*
